### PR TITLE
 Initial implementation of the LES protocol and its flow control.

### PR DESCRIPTION
**Pull request by zah**
The sync modules will be committed after some additional clean-up.

This also restores the old module structure of having separate
`peer_pool` and `rlpx` modules. This is made possible by the
new Nim package [package_visible_types](https://github.com/zah/nim-package-visible-types) (please refer to its
README for an explanation).

Also introduces more error handling in the low-level RLPx routines.
All detected errors will result in immediate disconnection of the
corresponding peer, which may be detected in the protocols though
the `onPeerDisconnected` event handler.

### CODE REVIEW

**Comment by yglukhov** [comment]
Got an error when building nimbus
```
../../nim-eth-p2p/eth_p2p/rlpx.nim(1050, 14) template/generic instantiation from here
../../nim-eth-p2p/eth_p2p/rlpx.nim(855, 18) template/generic instantiation from here
../../nim-eth-p2p/eth_p2p/rlpx.nim(173, 42) Error: attempting to call undeclared routine: 'readRecordType'
```

**Comment by yglukhov** [comment]
I'm on the fence about `package_visible_types`. Do we really want encapsulation so bad that are ready to resort to all kinds of macro hackery, and arguably sacrifice readability, and make the code learning curve  steeper?

**Comment by zah** [comment]
I created `package_visible_types` partly to move forward the cyclic dependencies debate - to shed more light and to reveal the true cost of the proposed alternatives. There is a "solution" now. If @Araq feels this is not an adequate approach to deal with the problem, he might do something about it :)

**Comment by yglukhov** [comment]
Ok, smart, but I think `package_visible_types` totally misses one important point of cyclic dependencies which is mutually dependent types (or procs or anything else) can be defined in different modules. I find it a lot more important than encapsulation. But that's probably not very relevant to this discussion.
So in what order do we merge all the prs now? :)

**Comment by zah** [comment]
@arnetheduck, considering that the alternatives right now are:

1) Make all fields in the types modules public
2) Merge back all modules into a single eth_p2p module
3) Keep using package_visible_types

I'd say option 3) is not that bad even if the master branch is not the place for political statements :)

**Comment by arnetheduck** [comment]
actually, I would go with 1):
* it's much more simple and easier to explain, as @yglukhov notes
* we're not supporting a public api that others depend upon
* we have full control over the code and can refactor at will
* it can be dealt with socially for now while the language gets developed (ie a comment is fine) - similar to how python does it - languages like nim I feel benefit much less from encapsulation

**Pull request merged**
