### PR TITLE
Rlpx fixes

### PR DESCRIPTION
**Pull request by yglukhov**
- Lazy init for `gProtocols` and `gCapabilities`.
- Fixed rlpx msgId off by 1
- Fixed rlpx decoding by entering the rlp list after msgId
- Thunk bodies are now emitted after all other definitions to be able to use those definitions in thunks
- Handle `ping` request

### CODE REVIEW

**Comment by arnetheduck** [comment]
in https://github.com/status-im/nim-eth-p2p/commit/a6b14dcd0bca368939c88f1fed574e6b8c78e776#r28821392 we discussed making an `EthClient` before we go too far with using these globals - is it better to address that before or after this PR?

**Comment by yglukhov** [comment]
What will `EthClient` be responsible for? To me `EthClient` sounds like an aggregate of `Server` + `PeerPool` + `Discovery`. `Peer` represents a single peer rlpx-over-tcp connection (not even discovery phase) and is maintained/created by either `Server` (incoming) or `PeerPool` (outgoing). As such capability configuration will need to be passed through a few levels, including the currently missing one `TheService` (or do you call it `EthClient`?) that manages both `Server`, `Discovery`, and `PeerPool`

**Comment by arnetheduck** [comment]
`EthClient` would hold whatever instance-specific/mutable data there is in those globals, so that they can be made immutable, at least conceptually.. I think that's about as deep as we went there - the point being that nim-eth-p2p should be usable as a library

**Comment by arnetheduck** [comment]
sure - just that this was not the way they functioned at the time of review - they also determined globally which features are enabled and it's that last bit that we agreed needs fixing

**Comment by zah** [comment]
Sure, this will be developed later. Yuriy's fix here is just to make the initialization kazy, which I assume was done in order to deal with initialization problems in the presence of cyclic imports.

**Pull request merged**
