### PR TITLE
Add snappy compression to RLPx (EIP-706)

### PR DESCRIPTION
**Pull request by data-man**
Not working yet.
I want to make sure that I'm on the right way. :-)

### CODE REVIEW

**Comment by cheatfate** [comment]
It looks like your wrapper is unsafe.

**Comment by zah** [comment]
@cheatfate, can you clarify what you noticed about the wrapper?

The code seems to insert `if` blocks in all the right places, but it's not clear to me what the issues were. I would recommend that you change the input types of the `libsnappyc` to use `openarray[byte]` though.

**Comment by cheatfate** [comment]
@zah, please check Appveyor tests.

**Comment by data-man** [comment]
@zah 

> but it's not clear to me what the issues were.

Just not working as expected. :-(
> I would recommend that you change the input types of the libsnappyc package to use openarray[byte] though.

I plan to port Snappy to pure Nim, but I'm not sure where: in the status-im or in NimCompression?

**Comment by zah** [comment]
Well, do we assume that the C port of snappy has such basic issues because it's less used? Seems a bit dubious to me, but nevertheless, we can also try the classic snappy lib, which actually also has a C interface:

https://github.com/google/snappy/blob/master/snappy-c.h

**Comment by data-man** [comment]
After adding the CIs tests, I discovered that the snappy-c [doesn't work on x32](https://github.com/NimCompression/nimsnappyc/blob/master/.appveyor.yml#L11).

**Pull request closed without merging**
